version: "3.1"
services:
    php:
        image: hiworks/develop-api:7.4
        container_name: blog-api-docker
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./apache2/default.conf:/etc/apache2/sites-enabled/default.conf
        ports:
            - "8088:80"
