version: "3.1"

services:
    php:
        image: hiworks/develop-api:7.4
        container_name: blog-api-docker
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./apache2/default.conf:/etc/apache2/sites-enabled/default.conf
        ports:
            - "8888:80"
        networks:
          - app-network

    db:
      container_name: mysql5
      image: mysql:5.7
      command:
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_unicode_ci
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: todo_list
        MYSQL_USER: devuser
        MYSQL_PASSWORD: devpass
      volumes:
        - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      ports:
        - "6666:3306"
      networks:
        - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
