version: "3.1"
services:
    php:
        image: hiworks/develop-api:7.4
        container_name: blog-api-docker
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./apache2/default.conf:/etc/apache2/sites-enabled/default.conf
        ports:
            - "8088:80"
        command: ['echo "\n\
                           xdebug.remote_host = "host.docker.internal" \n\
                           xdebug.idekey=PHPSTORM \n\
                           xdebug.default_enable = 1 \n\
                           xdebug.remote_autostart = 1 \n\
                           xdebug.remote_connect_back = 0 \n\
                           xdebug.remote_enable = 1 \n\
                           xdebug.remote_handler = "dbgp" \n\
                           xdebug.remote_port = 9000 \n\
                           " >> /etc/php/7.4/cli/conf.d/20-xdebug.ini']
